name = "rollcallplus-api"
main = "src/index.js"
compatibility_date = "2025-05-23"

[vars]
RAILWAY_BACKEND_URL = "https://rollcallplus-production.up.railway.app"
USE_NATIVE_SCRAPER = "true"
NATIVE_FALLBACK_TO_RAILWAY = "false"

[[kv_namespaces]]
binding = "SUPPORT_TICKETS"
id = "5310be13379349a3bd0883eaa51a2a44"
